### PR TITLE
Localization

### PR DESCRIPTION
**Pull request by kkslider-dev**
- feat: add languages in name attribute

### CODE REVIEW

**Comment by iamartwo** [comment]
I love this project and I think the localization could be a really great feature. But, I'm not sure that it's the best idea to edit all jsons files to add this feature. It could be better to have a new table in a database dedicated to the translation of strings, what do you think?

**Comment by jefflomacy** [comment]
I am in favor of modifying the JSON structures to support localizations because it maintains the data in one location. It's a major update but I believe such is the nature of this project until we really get the schema right for many things. Maintaining all of the localizations in one location seems the most straightforward to me. There may be duplication but the amount of duplication occurring is not expensive from a storage perspective. Anything consuming the files just needs to choose a route to get to localized information, as opposed to requiring access to another datasource to get names for a specific language.

However this is actively open to discussion and I am open to hearing drawbacks to keeping all the data in the existing JSON files.

**Comment by kkslider-dev** [comment]
In focused on getting a new version of the localizations with also the variants. I'll probably probably maintain they separates as suggested by @iamartwo because is easier to keep pulling the changes on files before this is accepted, but after the main code is aware of this ticket changes I can't see any reason to keep them separated. Maybe could have sense for variants, due repetitions.

We have discussed a little how to implement localizations on the discord of the app, it could be helpful bring it here. The main discussion is about elastic search indexes.

**Comment by jefflomacy** [comment]
From one of my messages in the discord... just so its in both places...

I think what we probably need to think about getting togetehr is a spreadsheet that has columns: id, type which will contain one row for every entity under data/villagers and data/items. we can then begin adding columns for localization import.
we would start by adding the existing name values from the json files into this spreadsheet, and we can begin adjusting from there.

I can create such a spreadsheet (initialized with data from the JSON) if we want to go that route? I can't think of an easier way to really manage this process. We could do one spreadsheet for villagers and another for items if we think that's easier. By the way, starting with villagers might be an easier trial run of this than attempting all the items to start, since we really only need to focus on name and catchphrases for the villagers. It would give us an opportunity to really iron things out before we go on the items and variations.

**Comment by kkslider-dev** [comment]
Added a python script to generate the localizations whenever they are needed instead of mantein the jsons already with localizations in this PR. This avoid conflicts when they are updated. The script is useful, but a draft after all.

**Comment by charlisepahina1** [comment]
@kkslider-dev any update of this script? i'm looking forward to translate them into chinese

**Comment by EijiAC24** [comment]
I can do Japanese let me know when it's ready👍

**Comment by trundler-dev** [comment]
Closing this as well - localization will be managed differently if/when we ever add it.

**Pull request closed without merging**
