### PR TITLE
Feature/label styles

### PR DESCRIPTION
**Pull request by jefflomacy**
Adds Fashion Theme (Labelle) styles to the search filters for New Horizons. Corrects a long-standing issue where search filter buckets were game-agnostic. This pull request fixes many issues with this, such as: You can no longer select Game:New Horizons and Personality:Snooty and find Ursala, as she has been Uchi since New Leaf. Similarly, you cannot select a game such as City Folk and find the personality of Uchi listed, because that personality did not exist prior to New Leaf.

Also, adds a counter next to each filter option, which is handy for debugging this and making sure the math lines up, but it's a useful end-user feature too, so it will stay.

### CODE REVIEW

**Comment by trundleroo** [comment]
Found an issue where narrowing by Fashion Theme does not properly narrow down the game. Example of "Cute" theme showing 11 items in New Horizons category, but New Horizons does not have the Cute theme. When you click the New Horizons filter, it shows no results. It seems that the search query is displaying the numbers of items in NH that _were_ cute in NH.

Reproduce:

- Go to Dresses
- Filter by Cute Fashion Theme
- Notice New Horizons filter displaying 11 results
- Click New Horizons filter, no results found.

**Comment by jefflomacy** [comment]
This should now be fixed. Please continue to test situations such as this. The solution to this was to build separate aggregations for each game bucket, pretending the game was selected in each bucket such that game-dependent documents that do not match other selections "fall out."

**Comment by jefflomacy** [comment]
Fixed another issue where Object.assign was causing stuff to leak all over the place and breaking URLs like /diy. This is fixed now.

**Comment by jefflomacy** [comment]
Closed some more loop holes in this by removing filters that no longer apply (bucket vanishes) when other filters are applied. Also, added bucket count to each filter (at the root, we already had it for the values in this branch).

**Review by trundleroo — APPROVED** [review]
QA: Many filter tests and fringe cases in the browser were performed, along with double checking that the math adds up for filter counts. From what I can tell, this feature is working as intended. Approved.

**Pull request merged**
