### PR TITLE
Getting Started Initial Walkthrough

### PR DESCRIPTION
**Pull request by arkamedus**
Adds ReadMe steps for developers to setup their local environment and get docker running the VillagerDB application

### CODE REVIEW

**Comment by trundleroo** [comment]
Closing this as I am going to update this guide in a different way.

**Comment by BboyAkers** [comment]
Why not use the GitHub code review tools to update this pull request for requesting changes instead??

**Comment by trundleroo** [comment]
@BboyAkers I could commit on top of this MR but it would essentially erase everything he already wrote. I am handling the Contributing section in the wiki.

**Comment by BboyAkers** [comment]
It's considered best practice to have the setup in the README.md in open source projects. This guide helped me get setup locally. His README.md looks the same but with more info. If you're wanting to add more merge his then update on top of that IMO.

**Comment by BboyAkers** [comment]
@trundleroo I'm not sure how familiar you are with managing an open source project but i'd be more than happy and give you a run down on what are best ways to manage an open source project 🙂 . Along with using the code review tools which are super helpful. @arkamedus @trundleroo @jefflomacy this pull request should be re-opened and merged due to I'll also be pushing a pull request soon as well just as a heads up.

**Comment by trundleroo** [comment]
@BboyAkers To clarify, we will have a contributing section in the README, but it will link to the Wiki. I would rather keep the README more terse than not and if there is simply a hotlink it is not difficult to find. Sorry for the confusion. We are still setting up our Contributing guidelines so we will have set process for PRs and the like soon. Hope that makes sense! If it's a matter of credit, I can definitely credit @arkamedus in the Wiki, however I would rather have him to speak to me about that, rather than someone else on his behalf.

**Comment by BboyAkers** [comment]
@arkamedus can definitely speak about it himself. I personally just saw a pull request on getting the project up and running, it helped me out, when I went back to look at issues and pull requests to take on I was wondering what happened to it. Seemed weird to me that a perfectly viable pull request was closed. Thank you for the clarification. 🙂

**Pull request closed without merging**
